config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "tasks#search", as: "search_tasks"
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users 
  namespace :admin do 
    resources :users
  end
   #root 'tasks#index'
  resources :tasks
end

app/models/task.rb
class Task < ApplicationRecord

    validates :name, presence: true 
    scope :search_by_title, -> (title ){ where("name LIKE ?","%#{title}%")}
    scope :search_by_status, -> (status) {where( status: status)}
    scope :search_by_label, -> (search_label){
        tasks = Labeling.where(label_id: search_label)
        ids = tasks.map{ |task| task.task_id } 
        where(id: ids)
    }
    scope :search_by_priority, -> (priority) {where( priority: priority)}
    scope :kaminari, -> (kaminari_pages){page(kaminari_pages).per(5)}
    paginates_per 50
    belongs_to :user, optional: true
    has_many :labelings, dependent: :destroy
    has_many :labels, through: :labelings, source: :label


    enum status: {
        unstarted: 0,
        progress: 1,
        completed: 2
    }

    enum priority: {
        low: 0,
        medium: 1,
        high: 2
    }
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = current_user.tasks.all.order(created_at: :desc).page(params[:page]).per(2)
    @tasks = current_user.tasks.all.order(ending_date: :desc).page(params[:page]).per(2) if params[:sort_expired] == 'true' 
    @tasks = current_user.tasks.all.order(priority: :desc).page(params[:page]).per(2) if params[:sort_priority] == 'true' 
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    @tasks = Task.all.page(params[:page]).per(2) if current_user.is_admin

      
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
    @labels = Label.all
  end

  # GET /tasks/1/edit
  def edit
    @labels = Label.all
  end

  # POST /tasks or /tasks.json
  def create
    @task = current_user.tasks.build(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: I18n.t('views.messages.create_task') }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: I18n.t('views.messages.update_task') }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end
  def search
    @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    session[:search] = {
      'name' => params[:search_title],
      'status' => params[:search_status],
      'priority' => params[:search_priority],
      'label'  => params[:search_label]
    }

    if params[:search_title].present?
      if params[:search_status].present?
        if params[:search_priority].present?
          if params[:search_label].present?
          @tasks = current_user.tasks.search_by_title(params[:search_title]).search_by_status(params[:search_status]).search_by_priority(params[:search_priority]).search_by_label(params[:search_label]).kaminari params[:page] 
          else 
            @tasks = current_user.tasks.search_by_title(params[:search_title]).search_by_status(params[:search_status]).search_by_priority(params[:search_priority]).kaminari params[:page] 
          end
        else
          @tasks = current_user.tasks.search_by_title(params[:search_title]).search_by_status(params[:search_status]).kaminari params[:page] 
        end
      elsif params[:search_priority].present?
        @tasks = current_user.tasks.search_by_title(params[:search_title]).search_by_priority(params[:search_priority]).kaminari params[:page] 
      else
        @tasks = current_user.tasks.search_by_title(params[:search_title]).kaminari params[:page] 

      end

    elsif params[:search_status].present?
      
      if params[:search_priority].present?
        if params[:search_label].present?
          @tasks = current_user.tasks.search_by_status(params[:search_status]).search_by_priority(params[:search_priority]).search_by_label(params[:search_label]).kaminari params[:page] 
        else
           @tasks = current_user.tasks.search_by_status(params[:search_status]).search_by_priority(params[:search_priority]).kaminari params[:page]
        end
          
      else
        @tasks = current_user.tasks.search_by_status(params[:search_status]).kaminari params[:page] 
      end

    elsif params[:search_priority].present?
      
      if params[:search_status].present?
        if params[:search_label].present?
          @tasks = current_user.tasks.search_by_priority(params[:search_priority]).search_by_status(params[:search_status]).search_by_label(params[:search_label]).kaminari params[:page]
        else
          @tasks = current_user.tasks.search_by_priority(params[:search_priority]).search_by_status(params[:search_status]).kaminari params[:page] 
        end
        
      else
        @tasks = current_user.tasks.search_by_priority(params[:search_priority]).kaminari params[:page] 
      end

    elsif params[:search_label].present?
      
      if params[:search_status].present?
        if params[:search_priority].present?
          @tasks = current_user.tasks.search_by_priority(params[:search_priority]).search_by_status(params[:search_status]).search_by_label(params[:search_label]).kaminari params[:page]
        else
          @tasks = current_user.tasks.search_by_label(params[:search_label]).search_by_status(params[:search_status]).kaminari params[:page] 
        end
        
      else
        @tasks = current_user.tasks.search_by_label(params[:search_label]).kaminari params[:page] 
      end
      
    else
      @tasks = current_user.tasks.kaminari params[:page] 
    end
    #@tasks = Task.all.kaminari params[:page] 
    # @labels = Label.where(user_id: nil).or(Label.where(user_id: current_user.id))
    render :index
  end


  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: I18n.t('views.messages.delete_task') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :content, :ending_date, :status, :priority, label_ids: [] )
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>
  <div class="field">
    <%= form.label :ending_date %>
    <%= form.datetime_select :ending_date %>
  </div>

 <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Task.statuses.keys %>
  </div>
  <div class="field">
    <%= form.label :priority %>
    <%= form.select :priority, Task.priorities.keys %>
  </div>
  
   <div class="row">
   <h4> label </h4>
      <% @labels.each do |label| %>
      <div class="col m-3 col-lg-2">
          <p>
            <%= form.check_box :label_ids, { multiple: true, checked: @task.labels.find_by(id: label.id).present?,  disabled: label[:disabled], include_hidden: false }, label[:id] %>
          <%=form.label :label_ids, label.name,value:label[:id],style:'text-decoration:none'%>
          </p>
        </div>
     <% end %>
     </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>

 <%= form_with(url: search_tasks_path, method: :get, local: true) do |f| %>
      <% if defined? @search_title %>
        <%= f.text_field :search_title,class:'form label mx-3', value: @search_title,style:'height:40px;width:200px'%>
      <% else %>
        <%= f.label 'Task name' %>
        <%= f.text_field :search_title, class:'form'%>
      <% end %>
       <%= f.select :search_status,
           Task.statuses.map { |k, v| [k, v] },
           class: 'search_status form-control',
           prompt: 'status'%>
       <%= f.select :search_priority,
           Task.priorities.map { |k, v| [k, v] },
           class: 'search_priority form-control',
           prompt: 'priority'%>
        <%= f.select :search_label,
            @labels.collect { |p| [p.name, p.id]},
             class: "search_label", 
             prompt: 'Tag' %>

 <%= f.submit 'search' ,class:'btn btn-light'%>

      <% end %>
<%= link_to 'New Task', new_task_path , class:' btn btn-primary btn-sm text-white'%>
<br>
<table class="table">
  <thead>
    <tr>
    <th> Published by </th>
      <th>Name</th>
      <th>Content</th>
       <th>Deadline</th>
       <th>Registered date</th>
      <th>Status</th>
      <th>Priority</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
      <%if Rails.env.test?%>
      <% else%>
          <td> <%= task.user.name%> </td> 
      <% end %>
        <td class="task_row"><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.ending_date %></td>
        <td><%= task.created_at %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task, class:'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_task_path(task) , class:'btn btn-outline-success btn-sm'%></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } , class:'btn btn-outline-danger btn-sm'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= paginate @tasks %>

<%= link_to "Sort by priority", tasks_path(sort_priority: "true"), class:"btn btn-secondary text-white" %>

<%= link_to "Sort by end deadline", tasks_path(sort_expired: "true"), class:"btn btn-secondary text-white"  %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @task.content %>
</p>
<p>
  <strong>Ending date:</strong>
  <%= @task.ending_date %>
</p>

<p>
  <strong>Label </strong>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>