config/routes.rb
Rails.application.routes.draw do
  get '/search', to: "tasks#search", as: "search_tasks"
  root 'sessions#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users 
  namespace :admin do 
    resources :users
  end
   #root 'tasks#index'
  resources :tasks
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { minimum: 4, maximum: 30 }
    validates :email, presence: true, length: { minimum: 5, maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true
    before_validation { email.downcase! }
    has_secure_password
    validates :password, length: { minimum:6 }
    has_many :tasks, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
        skip_before_action :login_required, only: [:new, :create]
       def new
           @user = User.new
       end
   
        def index
            if current_user.is_admin
                @users = User.all.where.not(id: current_user.id)
            else
                redirect_to tasks_path, notice:"Vous n'etes pas administrateur"
            end

        end
       def create
           @user = User.new(user_params)
           if @user.save
               redirect_to admin_users_path
           else
               render :new
           end
       end
       def update
            @user = User.find(params[:id])
            if @user.update(user_params) 
                redirect_to admin_users_path
            else
                render :edit
            end

        end
        def show
            @user = User.find(params[:id])
            if current_user != @user.id
                redirect_to tasks_path
            else
                @tasks= @user.tasks.all.page(params[:page]).per(2)
            end
        end
       def edit
        @user = User.find(params[:id])
       end
       
       private
       def user_params
           params.require(:user).permit(:name, :email, :password, :password_confirmation, :is_admin)
       end
      
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     skip_before_action :login_required, only: [:new, :create]
    def new
        @user = User.new
        if current_user
            redirect_to tasks_path
        else
            @user = User.new
        end

    end
    def update
        @user = User.find(params[:id])
        @user.update(user_params) 
        if @user.save
            redirect_to user_path
        end
    end

    def edit
        @user = User.find(params[:id])
   end
    def index
    
    end
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_users_path            
    
    end

    def create
        @user = User.new(user_params)
        if @user.save     
            session[:user_id] = @user.id
            redirect_to tasks_path

        else
            render :new
        end
    end

    def show
        @user = User.find(params[:id])

        if current_user.id != @user.id 
            redirect_to tasks_path
                    
        elsif current_user.is_admin != true && current_user.id != @user.id
            redirect_to tasks_path

        end  
            
            @tasks= @user.tasks.all.page(params[:page]).per(2)
        
    end

    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
    <% if @user.errors.any? %>
          <div id="error_explanation">
          <h2> il y a <%= @user.errors.count %> erreurs</h2>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
          </ul>
          </div>
       <% end %>
    <div class="container">
        <div class="side-one">
            <div class="logo">
            </div>
        </div>
        <div class="side-nd">
            <div class="form">
              <%= form_with(model: [:admin ,@user], local: true) do |f| %> 
                <%= f.text_field :name, class:"field", placeholder: 'Nom' %> 
                <%= f.email_field :email , class:"field", placeholder: 'Adresse e-mail' %>
                <%= f.label 'Nommer admin'%>
                <%= f.check_box :is_admin, class:'field'%>
                <%= f.password_field :password, class:"field", placeholder: 'Nouveau mot de passe' %>  
                 <%= f.password_field :password_confirmation, class:"field", placeholder: 'Confirmation de mot de passe' %> 

                <%= f.submit "Update account",class:"btnlog" %>
                 <%= link_to "Back", admin_users_path%> 
                <% end %>
               
            </div>
        </div>
        
    </div> 
    

app/views/admin/users/index.html.erb
<h1>users</h1>

<%= link_to 'New User', new_admin_user_path , class:' btn btn-primary btn-sm text-white'%>
<br>
<table class="table">
  <thead>
    <tr>
    <th> User name  </th>
      <th>Email</th>
      <th> Tasks number </th>
      <th> Rule </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      <td> <%= user.name%> </td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td> <% if user.is_admin%>
        Admin<% else%> 
        General user</td>
        <% end %>

        <td><%= link_to 'Show profil', admin_user_path(user.id), class:'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_admin_user_path(user.id) , class:'btn btn-outline-success btn-sm'%></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } , class:'btn btn-outline-danger btn-sm'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/admin/users/new.html.erb
<%
=begin%>
 <h1>Sign up</h1> 
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2> il y a <%= @user.errors.count %> erreurs</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <%= form_with(model: @user, local: true) do |f| %> 
 <%= f.label :Name %> 
 <%= f.text_field :name %> 
 <%= f.label :Email %> 
 <%= f.email_field :email %> 
 <%= f.label :Password %> 
 <%= f.password_field :password %> 
 <%= f.label :Password_confirmation %> 
 <%= f.password_field :password_confirmation %> 
 <%= f.submit "Create my account" %> 
 <% end %> 
<%
=end%>
<html>
    <head>
       <% if @user.errors.any? %>
          <div id="error_explanation">
          <h2> il y a <%= @user.errors.count %> erreurs</h2>
          <ul>
          <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
          </ul>
          </div>
       <% end %>
    </head>
    <body>  
    <div class="container">
        <div class="side-one">
            <div class="logo">
            </div>
        </div>
        <div class="side-nd">
            <div class="form">
              <%= form_with(model: [:admin ,@user], local: true) do |f| %> 
                <%= f.text_field :name, class:"field", placeholder: 'Nom' %> 
                <%= f.email_field :email , class:"field", placeholder: 'Adresse e-mail' %>
                <%= f.password_field :password, class:"field", placeholder: 'Nouveau mot de passe' %>  
                 <%= f.password_field :password_confirmation, class:"field", placeholder: 'Confirmation de mot de passe' %> 

                <%= f.submit "Create account",class:"btnlog" %>
                <% end %>
                <% if logged_in? %> 
                <%= link_to "Profile", user_path(current_user.id) %>
                <%= link_to "Logout", session_path(current_user.id), method: :delete %>
                <% else%> 

                <% link_to "Sign up", new_user_path  %>
                <%= link_to "Login", new_session_path ,class:"btlog"%>
                <% end%> 
            </div>
            <div class="item"> <%= link_to "Back", admin_users_path%>  </div>
        </div>
        
    </div> 
    

    </body>     
</html>

app/views/admin/users/show.html.erb
<<h1>Tasks</h1>

 <%= form_with(url: search_tasks_path, method: :get, local: true) do |f| %>
      <% if defined? @search_title %>
        <%= f.text_field :search_title,class:'form label mx-3', value: @search_title,style:'height:40px;width:200px'%>
      <% else %>
        <%= f.label 'Task name' %>
        <%= f.text_field :search_title, class:'form'%>
      <% end %>
       <%= f.select :search_status,
           Task.statuses.map { |k, v| [k, v] },
           class: 'search_status form-control',
           prompt: 'status'%>
       <%= f.select :search_priority,
           Task.priorities.map { |k, v| [k, v] },
           class: 'search_priority form-control',
           prompt: 'priority'%>

 <%= f.submit 'search' ,class:'btn btn-light'%>

      <% end %>
<%= link_to 'New Task', new_task_path , class:' btn btn-primary btn-sm text-white'%>
<br>
<table class="table">
  <thead>
    <tr>
    <th> Published by </th>
      <th>Name</th>
      <th>Content</th>
       <th>Deadline</th>
       <th>Registered date</th>
      <th>Status</th>
      <th>Priority</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
      <td> <%= task.user.name%> </td>
        <td class="task_row"><%= task.name %></td>
        <td><%= task.content %></td>
        <td><%= task.ending_date %></td>
        <td><%= task.created_at %></td>
        <td><%= task.status %></td>
        <td><%= task.priority %></td>
        <td><%= link_to 'Show', task, class:'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Edit', edit_task_path(task) , class:'btn btn-outline-success btn-sm'%></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } , class:'btn btn-outline-danger btn-sm'%></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= paginate @tasks %>

<%= link_to "Sort by priority", tasks_path(sort_priority: "true"), class:"btn btn-secondary text-white" %>
<h1> Details </h1>
<p> Name :<%= @user.name %> </p>
<p> Email :<%=@user.email %> </p>

<br>
<%= link_to "Sort by end deadline", tasks_path(sort_expired: "true"), class:"btn btn-secondary text-white"  %>


<%= link_to "Back", admin_users_path %>